### ISSUE TITLE
ux: `ua status`

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#719]
# Work Items

- [x] Add column headers to all columns
- [x] Move the account information to the bottom
- [x] Entitled can be one of: yes or no. It states whether your contract has entitled you to that service on this release. For example, on Bionic a community member would be entitled to cis-audit and it would say yes, but that service is not available on Trusty, so say no.
- [ ] Status is whether or not it is enabled on the system. It is one of: enabled, disabled, n/a, or an em dash (e.g. '—'). It is n/a if it is possible to enable it, but not in the current state. For example, on Trusty if you are not running the HWE kernel, livepatch is 'n/a'. Services not available on the current release will be the EM dash. I believe this also means if the entitlement is no, then it will also be a dash.
- [x] Default descriptions for all services need to be added to the classes. These will be placed in the new description field.
- [ ] Custom descriptions will be received from the backend server. When these are present based on different scenarios they should be presented to the user.

# Examples

A user is attached with a community token:

```
$ sudo ua status
SERVICE       ENTITLED  STATUS    DESCRIPTION
cc-eal        no        —         Common Criteria EAL2 Provisioning Packages
cis-audit     no        —         Center for Internet Security Audit Tools
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance
fips          no        —         NIST-certified FIPS modules
fips-updates  no        —         Uncertified security updates to FIPS modules
livepatch     yes       n/a       Available with the HWE kernel

Enable services with: sudo ua enable <service>

     Account: josh.powers@canonical.com
Subscription: josh.powers@canonical.com
```

A user is attached with UA Essential, with the HWE kernel:

```
$ sudo ua status
SERVICE       ENTITLED  STATUS    DESCRIPTION
cc-eal        no        —         Common Criteria EAL2 Provisioning Packages
cis-audit     no        —         Center for Internet Security Audit Tools
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance
fips          no        —         NIST-certified FIPS modules
fips-updates  no        —         Uncertified security updates to FIPS modules
livepatch     yes       disabled  Canonical Livepatch service

Enable services with: sudo ua enable <service>

                Account: UA Client Test
           Subscription: UA Client Test Contract
            Valid until: 2020-12-31
Technical support level: essential
```

**Comment by OddBloke** [comment]
FYI, I've started rewriting the docs and man page to match the expected behaviour as part of #722

**Comment by OddBloke** [comment]
Still seeing:

```
livepatch     yes       —         Canonical Livepatch service
```

**Comment by OddBloke** [comment]
I've moved the two remaining pieces of work into #789 and #790, so we can close this omnibus issue out.
